version: "3.9"

services:
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    image: frontend-react:latest # Nombre de la imagen del frontend
    networks:
      - researcher-network-webapp_default
    volumes:
      - ./frontend-react:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - ./frontend-react/.env

  backend:
    build:
      context: ./backend-django
      dockerfile: Dockerfile
    image: researcher-network-webapp-backend:latest # Nombre de la imagen del backend
    networks:
      - researcher-network-webapp_default
    volumes:
      - ./backend-django/ev2project:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend-django/ev2project/ev2/.env

networks:
  researcher-network-webapp_default:
    external: true # Usando la red externa que mencionaste
