version: "3.9"

services:
  backend:
    build:
      context: ./backend-django
      dockerfile: Dockerfile
    volumes:
      - ./backend-django/ev2project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-react # Aquí apuntas a la carpeta correcta frontend-react
      dockerfile: Dockerfile
    volumes:
      - ./frontend-react:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
