services:
  backend:
    build: ./backend-django
    container_name: ev2-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend-django:/app
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: gunicorn --bind 0.0.0.0:8000 ev2.wsgi:application
    restart: unless-stopped
    networks:
      - ev2-network

  frontend:
    build: ./frontend-react
    container_name: ev2-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ev2-network

networks:
  ev2-network:
    driver: bridge