apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django
          image: gcr.io/kuberentes-ai/django-backend
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: "investigadores"
            - name: DB_USER
              value: "avnadmin"
            - name: DB_PASSWORD
              value: "AVNS_OJl9GHlYv4ao6EjkYMX"
            - name: DB_HOST
              value: "investigadores-alfaro-07b5.k.aivencloud.com"
            - name: DB_PORT
              value: "24478"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
